### ISSUE TITLE
Approaching Artificial Intelligence as an Embodied Developmental Process

### ISSUE THREAD

**Issue by jesparent** [OREL-group/Meta-brain-Models#2]

**Comment by Orthogonal-Research-Lab** [comment]
Requested that video be made public at NM3. Blog post TBA.

**Comment by jesparent** [comment]
@Orthogonal-Research-Lab  - was this a neuormatch submission?

**Comment by Orthogonal-Research-Lab** [comment]
No, this was for IGSS: https://www.igss-workshop.org/

**Comment by EXYNOS-999** [comment]
Did we already submit an extended abstract @ IGSS?

**Comment by jesparent** [comment]
I think whatever this was (appears NM3 related? is settled?) @balicea  @Orthogonal-Research-Lab
