### ISSUE TITLE
SURe - Feb 15

### ISSUE THREAD

**Issue by jesparent** [OREL-group/Meta-brain-Models#6]
Scientific Understandings of Representations - (observer dependent models etc)

**Comment by devoworm** [comment]
Submitted before February 15 deadline, will hear back soon.

**Comment by Athene-ai** [comment]
perfect !


<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Mail
priva di virus. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by jesparent** [comment]
@Orthogonal-Research-Lab do we know when we'll hear back from this?

**Comment by devoworm** [comment]
March 1

**Comment by jesparent** [comment]
@Orthogonal-Research-Lab  I think this was a reject or no-go with this right? closing out
